name: Frontend CI

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend-app
        run: npm ci

      - name: Run lint
        working-directory: frontend-app
        run: npm run lint


  security:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: frontend-app
        run: npm ci

      - name: Dependency security scan
        working-directory: frontend-app
        run: npm audit --audit-level=high --registry=https://registry.npmjs.org/

      - name: Secret scan
        run: gitleaks dir . --redact


  build:
    needs:
      - lint
      - security

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend-app
        run: npm ci

      - name: Run build
        working-directory: frontend-app
        run: npm run build

  docker:
    needs:
      - lint
      - security
      - build

    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend-app
        run: npm ci

      - name: Run build
        working-directory: frontend-app
        run: npm run build

      - name: Build Docker image
        working-directory: frontend-app
        run: docker build -t frontend-app:${{ github.sha }} .

      - name: Check AWS identity
        shell: powershell
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: Login to ECR
        shell: powershell
        run: |
          $password = aws ecr get-login-password --region eu-central-1
          $password | docker login --username AWS --password-stdin 893089245803.dkr.ecr.eu-central-1.amazonaws.com

      - name: Tag Docker image  
        run: docker tag frontend-app:${{ github.sha }} 893089245803.dkr.ecr.eu-central-1.amazonaws.com/docker-images/frontend-app:${{ github.sha }}

      - name: Push Docker image
        run: docker push 893089245803.dkr.ecr.eu-central-1.amazonaws.com/docker-images/frontend-app:${{ github.sha }}